name:       libxlsxwriter
version:    0.0.2
synopsis:   Excel file generation (libxslxwriter)
maintainer: Blake Rain <blake.rain@gmail.com>
license:    BSD3
build-type: Simple

dependencies:
  - base
  - data-default
  - time

ghc-options: -Wall -O2

library:
  exposed-modules:
    - Data.Excel
  source-dirs:
    - src
  include-dirs:
    - thirdparty/include
  c-sources:
    - thirdparty/src/app.c
    - thirdparty/src/chart.c
    - thirdparty/src/content_types.c
    - thirdparty/src/core.c
    - thirdparty/src/custom.c
    - thirdparty/src/drawing.c
    - thirdparty/src/format.c
    - thirdparty/src/hash_table.c
    - thirdparty/src/packager.c
    - thirdparty/src/relationships.c
    - thirdparty/src/shared_strings.c
    - thirdparty/src/styles.c
    - thirdparty/src/theme.c
    - thirdparty/src/utility.c
    - thirdparty/src/workbook.c
    - thirdparty/src/worksheet.c
    - thirdparty/src/xmlwriter.c
    - thirdparty/third_party/minizip/ioapi.c
    - thirdparty/third_party/minizip/zip.c
    - thirdparty/third_party/tmpfileplus/tmpfileplus.c
  extra-libraries:
    - z

executables:
  excel-test1:
    main: excel-test1.hs
    source-dirs: test
    dependencies:
      - libxlsxwriter

  
